blog: stryker-js 7
stryker-mutator/stryker-mutator.github.io pull request #635
Opened 2023-06-02 17:51 UTC by nicojs

2023-06-02 17:52 UTC, nicojs commented
@danny12321 @odinvanderlinden  would you mind taking a look?

2023-06-05 07:28 UTC, danny12321 requested changes
The text looks good, but left one comment about an emoji.

2023-06-05 07:28 UTC, danny12321 commented on blog/2023-06-05-announcing-stryker-js-7.0.md
> +## 🪹 Allow empty
This emoji is not recognized by my browser, which is chrome.

2023-06-05 07:28 UTC, danny12321 requested changes
The text looks good, but left one comment about an emoji.

2023-06-05 10:21 UTC, merged

2023-06-05 10:23 UTC, nicojs commented
Thanks! I've changed the empty nest (🪹) emoji with an empty mailbox (📭) emoji :)